export const FETCH_MOVIES_START = 'FETCH_MOVIES_START';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';

export const FETCH_MOVIES_BY_SEARCH_START = 'FETCH_MOVIES_BY_SEARCH_START';
export const FETCH_MOVIES_BY_SEARCH_SUCCESS = 'FETCH_MOVIES_BY_SEARCH_SUCCESS';

export const FETCH_MOVIE_BY_ID_START = 'FETCH_MOVIE_BY_ID_START';
export const FETCH_MOVIE_BY_ID_SUCCESS = 'FETCH_MOVIE_BY_ID_SUCCESS';
export const FETCH_CHANNEL = 'FETCH_CHANNEL';

export const NO_MORE_VIDEOS = 'NO_MORE_VIDEOS';


